---
# tasks file for sudo

- name: INCLUDE | Include get-vars.yml
  include: get-vars.yml

- name: INCLUDE | Include set-vars.yml
  include: set-vars.yml

- name: RUN INSTALL | Run FreeBSD installation
  include:  FreeBSD-install.yml
  when: ansible_os_family == "FreeBSD"

- name: CONFIG | FreeBSD config
  include: config.yml
  